name: Lint

on: [push]

jobs:
  get-pnpm-version:
    runs-on: ubuntu-latest
    outputs:
      pnpm-version: ${{ steps.get-version.outputs.pnpm-version }}
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: |
          content=`cat package.json | awk -F'"' '/"packageManager"/ {print $4}' | awk -F'@' '{print $2}'`
          echo "pnpm-version=$content" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    needs: get-pnpm-version
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: 20
          pnpm-version: ${{ needs.get-pnpm-version.outputs.pnpm-version }}
      - name: Run lint
        run: pnpm lint